name: Build Spring App


# Déclencher le workflow lors du push de l'application
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # étape 1: cherchez dans le marketplace l'action pour configurer le jdk
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17' 
            
            # étape 2: récupération du projet
            - name: Checkout project
              uses: actions/checkout@v4

            - name: Cache local Maven repository
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-

            # étape 3: installation des dépendances
            - name: Install dependencies
              run: mvn dependency:resolve

            # étape 4: build de l'application
            - name: Build de l'application
              run: mvn clean package

            # etape : upload du .jar comme artefact telechargable
            - name: Upload build artifact
              uses: action/upload-artifact@v4
              with:
                name: spring-app-jar
                path: target/*.jar
